# SPDX-License-Identifier: AGPL-3.0-only
# (c) 2026 Vahini Technologies.
#
# generate_photo_sample.py: builds frontend/scripts/core/sample-report-data.js,
# the data behind sample-report.html, by running the REAL server pipeline
# (OCR, layout, 20-factor scoring and evidence crops) on the photo in
# tests/fixtures/handwriting-sample.jpg.
#
# Why a photo and not the synthetic page: the free report shows the
# visitor's photo with an example cropped for each factor. A sample report
# without a photo cannot show what a visitor will actually get.
#
# Why this photo: it is already committed as the end-to-end test fixture and
# holds only practice sentences, no names or other personal data, so it is
# within the CONTRIBUTING.md rule on real handwriting.
#
# Needs the OCR models, so run it inside the analyser image:
#
#     docker run --rm -v "$PWD":/w -w /w --entrypoint python \
#       vahini/analyser:<tag> docs/examples/generate_photo_sample.py
#
# OCR output can move slightly between model versions, so this file is
# regenerated on purpose, not checked in CI.

import asyncio
import base64
import importlib.util
import json
import os
import sys

import cv2

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PHOTO = os.path.join(ROOT, "tests", "fixtures", "handwriting-sample.jpg")
OUT = os.path.join(
    ROOT, "frontend", "scripts", "core", "sample-report-data.js"
)
sys.path.insert(0, os.path.join(ROOT, "backend"))


def load_server():
    spec = importlib.util.spec_from_file_location(
        "sample_server", os.path.join(ROOT, "backend", "ppocr-server.py")
    )
    server = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(server)
    return server


def photo_data_url(arr, max_w=900, quality=72):
    """The photo as the report shows it: downscaled JPEG, like the browser's
    compressImageURL, so the page stays light."""
    height, width = arr.shape[:2]
    scale = min(1.0, max_w / float(width))
    if scale < 1.0:
        arr = cv2.resize(
            arr,
            (round(width * scale), round(height * scale)),
            interpolation=cv2.INTER_AREA,
        )
    ok, buf = cv2.imencode(".jpg", arr, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        raise SystemExit("could not encode the sample photo")
    return "data:image/jpeg;base64," + base64.b64encode(buf).decode("ascii")


def trim_whole_page(regions):
    """Whole-page factors repeat a ~130 KB copy of the page as their "crop".
    The report never shows it (it says the factor is measured across the
    page), so keep the region and its box but not the image."""
    out = {}
    for key, region in regions.items():
        box, size = region.get("bbox"), region.get("source_size")
        whole = (
            isinstance(box, list)
            and len(box) == 4
            and isinstance(size, list)
            and len(size) == 2
            and box[2] * box[3] > 0.8 * size[0] * size[1]
        )
        out[key] = dict(region, url="") if whole else region
    return out


def main():
    server = load_server()
    with open(PHOTO, "rb") as f:
        raw = f.read()
    arr = asyncio.run(server._decode_upload(raw))
    payload = server._report_python_process(arr, raw, "auto", "")
    if not payload.get("ok"):
        raise SystemExit(f"pipeline refused the sample: {payload}")
    lines = payload.get("hand_lines") or []
    text = payload.get("full_text") or "\n".join(
        ln.get("text", "") for ln in lines if ln.get("text")
    )
    data = {
        "analysis": payload["analysis"],
        "sample": {
            "nLines": len(lines),
            "nWords": len(text.split()),
            "nChars": len(text.replace(" ", "").replace("\n", "")),
            "text": text,
        },
        "photo": photo_data_url(arr),
        "factor_regions": trim_whole_page(payload.get("factor_regions") or {}),
    }
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "/* Generated by docs/examples/generate_photo_sample.py - do not"
            " edit by hand.\n"
            "   Real server output (OCR, scoring and evidence crops) for the"
            " photo in\n"
            "   tests/fixtures/handwriting-sample.jpg; sample-report.html"
            " renders it\n"
            "   through the same VahiniReport renderer the live pipeline"
            " uses. */\n"
        )
        f.write("window.VAHINI_SAMPLE_REPORT = ")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    analysis = payload["analysis"]
    print(
        f"wrote {os.path.relpath(OUT, ROOT)}: overall {analysis.get('overall')},"
        f" {len(data['factor_regions'])} factor crops,"
        f" {os.path.getsize(OUT) // 1024} KB"
    )


if __name__ == "__main__":
    main()
