/* SPDX-License-Identifier: AGPL-3.0-only */
/* Original Vahini worksheet metadata. Generated by the website worksheet catalogue. */
window.VahiniWorksheetCatalog = [
  {
    "id": "letter-shapes",
    "title": "Clear letter shapes",
    "factors": [
      1,
      3
    ]
  },
  {
    "id": "letter-size",
    "title": "Steady letter size",
    "factors": [
      5,
      6
    ]
  },
  {
    "id": "word-spacing",
    "title": "Give words room",
    "factors": [
      8,
      9
    ]
  },
  {
    "id": "baseline",
    "title": "Stay on the line",
    "factors": [
      7,
      11,
      12
    ]
  },
  {
    "id": "slant",
    "title": "Choose a steady slant",
    "factors": [
      17
    ]
  },
  {
    "id": "letter-distinction",
    "title": "Make similar letters distinct",
    "factors": [
      19
    ]
  },
  {
    "id": "smooth-strokes",
    "title": "Comfortable, clear strokes",
    "factors": [
      4,
      15
    ]
  },
  {
    "id": "page-layout",
    "title": "Give your page a clear layout",
    "factors": [
      10,
      20
    ]
  }
];
